on: push
name: ci
jobs:
  build:
    name: Test
    strategy:
      matrix:
        ruby: [2.5, 2.6, 2.7]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: script/cibuild
        run: script/cibuild
